"use client";

import React, { useState } from 'react';
import { useReading } from '@/lib/store';
import { FileText, Layers, BookOpen, Clock, Tag, Plus, Trash2, Save, PenLine, Maximize2, X } from 'lucide-react';
import Link from 'next/link';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { ko } from 'date-fns/locale';

export default function MyPage() {
    const { currentUser, journalPosts, books, addJournalPost, deleteJournalPost, updateJournalPost } = useReading();
    const [activeTab, setActiveTab] = useState<'journal' | 'materials' | 'memo'>('journal');
    const [memoInput, setMemoInput] = useState('');
    const [editingMemoId, setEditingMemoId] = useState<string | null>(null);
    const [editingMemoContent, setEditingMemoContent] = useState('');
    const [viewingMemo, setViewingMemo] = useState<any | null>(null);

    const handleAddMemo = async () => {
        if (!memoInput.trim() || !currentUser) return;

        const lines = memoInput.trim().split('\n');
        const title = lines[0].length > 30 ? lines[0].substring(0, 30) + '...' : lines[0];

        // Add new memo directly
        addJournalPost({
            id: '', // Generated by store/DB
            user_id: currentUser.id,
            category: 'memo',
            title: title || '무제 메모',
            content: memoInput.replace(/\n/g, '<br>'), // Simple line break handling
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        });

        setMemoInput('');
    };

    const handleStartEdit = (post: any) => {
        setEditingMemoId(post.id);
        // Convert <br> back to newlines for editing
        setEditingMemoContent(post.content.replace(/<br>/g, '\n'));
    };

    const handleOpenMemoModal = (post: any) => {
        setViewingMemo(post);
        setEditingMemoContent(post.content.replace(/<br>/g, '\n'));
    };

    const handleCloseMemoModal = () => {
        setViewingMemo(null);
        setEditingMemoContent('');
    };

    const handleSaveEdit = async (postId: string) => {
        if (!editingMemoContent.trim()) return;

        const lines = editingMemoContent.trim().split('\n');
        const title = lines[0].length > 30 ? lines[0].substring(0, 30) + '...' : lines[0];

        await updateJournalPost(postId, {
            title: title || '무제 메모',
            content: editingMemoContent.replace(/\n/g, '<br>')
        });

        setEditingMemoId(null);
        if (viewingMemo) {
            setViewingMemo(null);
        }
        setEditingMemoContent('');
    };

    const handleCancelEdit = () => {
        setEditingMemoId(null);
        setEditingMemoContent('');
    };

    if (!currentUser) {
        return (
            <div className="max-w-4xl mx-auto px-6 py-16 text-center">
                <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <FileText size={32} className="text-gray-400" />
                </div>
                <h1 className="text-2xl font-bold text-[#37352F] mb-2">로그인이 필요합니다</h1>
                <p className="text-[#787774]">나의 활동 기록을 보려면 먼저 로그인해 주세요.</p>
            </div>
        );
    }

    // Filter posts by current user
    const myPosts = journalPosts.filter(p => p.user_id === currentUser.id);

    // Split into Journal (excluding idea & simple memo), Materials (idea), and Memos (simple memo without book)
    const myJournals = myPosts.filter(p => p.category !== 'idea' && !(p.category === 'memo' && !p.book_id)).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    const myMaterials = myPosts.filter(p => p.category === 'idea').sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    const myMemos = myPosts.filter(p => p.category === 'memo' && !p.book_id).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

    const getBookTitle = (bookId?: string) => {
        if (!bookId) return '자유 주제';
        return books.find(b => b.id === bookId)?.title || '삭제된 도서';
    };

    const getCategoryLabel = (category: string) => {
        switch (category) {
            case 'question': return '질문';
            case 'feeling': return '느낀점';
            case 'memo': return '메모 및 요약';
            case 'idea': return '아이디어';
            default: return '기타';
        }
    };

    return (
        <div className="max-w-[1200px] mx-auto px-6 py-10 md:px-12 md:py-16">
            {/* Header / Profile */}
            <div className="flex items-end justify-between mb-10 border-b border-[#EBEBEB] pb-8">
                <div className="flex items-center gap-6">
                    <div className="w-20 h-20 bg-[#37352F] rounded-full flex items-center justify-center text-3xl font-bold text-white shadow-lg">
                        {currentUser.name?.charAt(0) || '나'}
                    </div>
                    <div>
                        <h1 className="text-3xl font-bold text-[#37352F] mb-1">{currentUser.name}님의 기록</h1>
                        <p className="text-[#787774] text-sm">
                            총 <span className="font-bold text-[#37352F]">{myPosts.length}</span>개의 활동 내역이 있습니다.
                        </p>
                    </div>
                </div>
            </div>

            {/* Tabs */}
            <div className="flex border-b border-[#EBEBEB] mb-8">
                <button
                    onClick={() => setActiveTab('journal')}
                    className={cn(
                        "flex items-center gap-2 px-6 py-3 text-sm font-bold border-b-2 transition-all",
                        activeTab === 'journal'
                            ? "border-[#37352F] text-[#37352F]"
                            : "border-transparent text-[#787774] hover:text-[#37352F]"
                    )}
                >
                    <FileText size={16} />
                    내 독서기록장
                    <span className="ml-1 text-xs bg-gray-100 px-2 py-0.5 rounded-full">{myJournals.length}</span>
                </button>
                <button
                    onClick={() => setActiveTab('materials')}
                    className={cn(
                        "flex items-center gap-2 px-6 py-3 text-sm font-bold border-b-2 transition-all",
                        activeTab === 'materials'
                            ? "border-[#37352F] text-[#37352F]"
                            : "border-transparent text-[#787774] hover:text-[#37352F]"
                    )}
                >
                    <Layers size={16} />
                    내 수업자료
                    <span className="ml-1 text-xs bg-gray-100 px-2 py-0.5 rounded-full">{myMaterials.length}</span>
                </button>
                <button
                    onClick={() => setActiveTab('memo')}
                    className={cn(
                        "flex items-center gap-2 px-6 py-3 text-sm font-bold border-b-2 transition-all",
                        activeTab === 'memo'
                            ? "border-[#37352F] text-[#37352F]"
                            : "border-transparent text-[#787774] hover:text-[#37352F]"
                    )}
                >
                    <PenLine size={16} />
                    메모장
                    <span className="ml-1 text-xs bg-gray-100 px-2 py-0.5 rounded-full">{myMemos.length}</span>
                </button>
            </div>

            {/* Memo Quick Input Area (Only visible on Memo tab) */}
            {activeTab === 'memo' && (
                <div className="mb-10 animate-fade-in-down">
                    <div className="bg-[#FFFDF5] border border-[#F5E6D3] rounded-2xl p-6 shadow-sm relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
                            <PenLine size={120} className="text-[#FFB84D]" />
                        </div>
                        <h3 className="text-sm font-bold text-[#37352F] mb-3 flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-[#FFB84D]"></span> 새 메모 작성
                        </h3>
                        <textarea
                            value={memoInput}
                            onChange={(e) => setMemoInput(e.target.value)}
                            placeholder="잊지 말아야 할 아이디어나 할 일을 기록해보세요..."
                            className="w-full h-32 bg-transparent border-none resize-none focus:outline-none text-[#37352F] text-base leading-relaxed placeholder:text-[#D1D1D1]"
                        />
                        <div className="flex justify-end mt-2 pt-4 border-t border-[#F5E6D3]/50">
                            <button
                                onClick={handleAddMemo}
                                disabled={!memoInput.trim()}
                                className="flex items-center gap-2 px-4 py-2 bg-[#37352F] text-white rounded-lg text-sm font-bold hover:bg-black transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <Save size={14} />
                                메모 저장
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Content */}
            <div className={cn(
                "grid gap-6",
                activeTab === 'memo' ? "grid-cols-1 md:grid-cols-2 lg:grid-cols-4" : "grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
            )}>
                {(activeTab === 'journal' ? myJournals : activeTab === 'materials' ? myMaterials : myMemos).map((post) => (
                    activeTab === 'memo' ? (
                        // Memo Card Style
                        <div key={post.id} className="group relative bg-[#FFFCF5] border border-[#F5E6D3] rounded-xl p-6 hover:shadow-md transition-all duration-300 flex flex-col min-h-[200px] hover:-translate-y-1">
                            <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                                <button
                                    onClick={(e) => {
                                        e.preventDefault();
                                        handleStartEdit(post);
                                    }}
                                    className="p-1.5 text-amber-500 hover:text-amber-700 hover:bg-amber-50 rounded-lg transition-colors"
                                >
                                    <PenLine size={14} />
                                </button>
                                <button
                                    onClick={(e) => {
                                        e.preventDefault();
                                        handleOpenMemoModal(post);
                                    }}
                                    className="p-1.5 text-blue-500 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors"
                                >
                                    <Maximize2 size={14} />
                                </button>
                                <button
                                    onClick={(e) => {
                                        e.preventDefault();
                                        if (confirm('이 메모를 삭제하시겠습니까?')) deleteJournalPost(post.id);
                                    }}
                                    className="p-1.5 text-rose-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors"
                                >
                                    <Trash2 size={14} />
                                </button>
                            </div>
                            {editingMemoId === post.id ? (
                                <div className="flex-1 flex flex-col gap-2">
                                    <textarea
                                        value={editingMemoContent}
                                        onChange={(e) => setEditingMemoContent(e.target.value)}
                                        className="w-full h-full min-h-[120px] bg-white/50 border border-[#F5E6D3] rounded-lg p-3 text-sm focus:outline-none focus:border-[#FFB84D] resize-none"
                                        autoFocus
                                    />
                                    <div className="flex justify-end gap-2">
                                        <button
                                            onClick={() => handleCancelEdit()}
                                            className="px-3 py-1.5 text-xs text-[#787774] hover:bg-black/5 rounded-md transition-colors"
                                        >
                                            취소
                                        </button>
                                        <button
                                            onClick={() => handleSaveEdit(post.id)}
                                            className="px-3 py-1.5 text-xs bg-[#37352F] text-white rounded-md hover:bg-black transition-colors"
                                        >
                                            저장
                                        </button>
                                    </div>
                                </div>
                            ) : (
                                <div
                                    className="flex-1 text-sm text-[#37352F] leading-relaxed whitespace-pre-wrap break-words"
                                    dangerouslySetInnerHTML={{ __html: post.content }}
                                />
                            )}
                            <div className="mt-4 pt-3 border-t border-[#F5E6D3]/50 flex items-center justify-between text-[10px] text-[#A1A1A1]">
                                <span>{format(new Date(post.created_at), 'MM.dd a h:mm', { locale: ko })}</span>
                            </div>
                        </div>
                    ) : (
                        // Journal/Material Card Style
                        <div key={post.id} className="bg-white border border-[#EBEBEB] rounded-2xl p-6 hover:shadow-lg hover:-translate-y-1 transition-all duration-300 flex flex-col h-[280px]">
                            <div className="flex items-center justify-between mb-4">
                                <span className={cn(
                                    "px-2.5 py-1 text-[10px] font-bold rounded uppercase",
                                    post.category === 'question' ? "bg-rose-50 text-rose-600" :
                                        post.category === 'idea' ? "bg-amber-50 text-amber-600" :
                                            post.category === 'feeling' ? "bg-green-50 text-green-600" :
                                                "bg-gray-100 text-gray-600"
                                )}>
                                    {getCategoryLabel(post.category)}
                                </span>
                                <span className="text-[11px] text-[#A1A1A1] flex items-center gap-1">
                                    <Clock size={12} />
                                    {format(new Date(post.created_at), 'yyyy.MM.dd', { locale: ko })}
                                </span>
                            </div>

                            <h3 className="text-lg font-bold text-[#37352F] mb-2 line-clamp-2 leading-tight min-h-[3rem]">
                                {post.title}
                            </h3>

                            <div className="flex items-center gap-1.5 mb-4 text-[#787774] text-xs">
                                <BookOpen size={14} className="text-blue-500" />
                                <span className="truncate">{getBookTitle(post.book_id)}</span>
                            </div>

                            <div
                                className="text-sm text-[#787774] line-clamp-3 mb-auto"
                                dangerouslySetInnerHTML={{ __html: post.content.replace(/<[^>]+>/g, '') }}
                            />

                            {/* Footer / Actions */}
                            <div className="pt-4 mt-4 border-t border-[#F1F1F0] flex items-center justify-between">
                                <div className="flex gap-1">
                                    {post.material_tags?.slice(0, 2).map(tag => (
                                        <span key={tag} className="px-2 py-0.5 bg-gray-50 text-gray-500 text-[10px] rounded">#{tag}</span>
                                    ))}
                                </div>
                                <Link
                                    href={activeTab === 'journal' ? `/journal?bookId=${post.book_id}` : '/contents'}
                                    className="text-xs font-bold text-blue-600 hover:underline"
                                >
                                    자세히 보기 →
                                </Link>
                            </div>
                        </div>
                    )
                ))}
            </div>

            {
                activeTab === 'journal' && myJournals.length === 0 && (
                    <div className="py-20 text-center border-2 border-dashed border-[#F1F1F0] rounded-3xl text-[#A1A1A1]">
                        <p>등록된 독서 기록이 없습니다.</p>
                    </div>
                )
            }

            {
                activeTab === 'materials' && myMaterials.length === 0 && (
                    <div className="py-20 text-center border-2 border-dashed border-[#F1F1F0] rounded-3xl text-[#A1A1A1]">
                        <p>등록된 수업 자료가 없습니다.</p>
                    </div>
                )
            }

            {
                activeTab === 'memo' && myMemos.length === 0 && (
                    <div className="py-20 text-center border-2 border-dashed border-[#F5E6D3] bg-[#FFFCF5]/30 rounded-3xl text-[#A1A1A1]">
                        <p>작성된 메모가 없습니다.</p>
                        <p className="text-sm mt-2">위의 입력창에 간단한 메모를 남겨보세요.</p>
                    </div>
                )
            }
            {viewingMemo && (
                <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-[100] flex items-center justify-center p-4" onClick={handleCloseMemoModal}>
                    <div className="w-full max-w-3xl bg-[#FFFDF5] rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] resize min-h-[500px]" onClick={e => e.stopPropagation()}>
                        <div className="flex items-center justify-between px-6 py-4 border-b border-[#F5E6D3] bg-[#FFFDF5]">
                            <h3 className="font-bold text-lg text-[#37352F] flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-[#FFB84D]"></span>
                                메모 수정
                            </h3>
                            <button onClick={handleCloseMemoModal} className="p-2 text-[#A1A1A1] hover:text-[#37352F] hover:bg-black/5 rounded-lg transition-colors">
                                <X size={20} />
                            </button>
                        </div>
                        <div className="flex-1 p-6 overflow-hidden">
                            <textarea
                                value={editingMemoContent}
                                onChange={(e) => setEditingMemoContent(e.target.value)}
                                className="w-full h-full bg-transparent border-none resize-none focus:outline-none text-[#37352F] text-lg leading-relaxed placeholder:text-[#D1D1D1]"
                                placeholder="내용을 입력하세요..."
                                autoFocus
                            />
                        </div>
                        <div className="px-6 py-4 border-t border-[#F5E6D3] bg-[#FFFDF5] flex justify-end gap-2">
                            <button
                                onClick={handleCloseMemoModal}
                                className="px-4 py-2 text-sm font-bold text-[#787774] hover:bg-black/5 rounded-lg transition-colors"
                            >
                                취소
                            </button>
                            <button
                                onClick={() => handleSaveEdit(viewingMemo.id)}
                                className="px-4 py-2 text-sm font-bold bg-[#37352F] text-white rounded-lg hover:bg-black transition-colors flex items-center gap-2"
                            >
                                <Save size={16} />
                                저장하기
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div >
    );
}
